name: Code-Climate-Coverage
on: [push, workflow_dispatch]
jobs:
  Code-Climate-Coverage:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install python3.10
      - run: python3.10 --version 
      - run: pwd
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ls -la
      - run: pip install pytest coverage
      - run: coverage run -m pytest tests/
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 6387c450c21d2766b4b96582b035e0ea88afbaa050ef510ce200725c911c2b56
        with:
          coverageCommand: coverage report
